services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5532:5432 # I faced a problem that i was running a postgres instance on my local machine in the default port, so when i changed it it worked properly
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
